-- MySQL Script generated by MySQL Workbench
-- Mon Mar 22 09:28:36 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema tweet_app
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tweet_app
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tweet_app` DEFAULT CHARACTER SET utf8 ;
USE `tweet_app` ;

-- -----------------------------------------------------
-- Table `tweet_app`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweet_app`.`user` (
  `user_id` VARCHAR(100) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `mobile_number` VARCHAR(10) NOT NULL,
  `url` VARCHAR(100),
  `gender` VARCHAR(1) NOT NULL,
  `dob` DATE NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `logged_in` TINYINT(1) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tweet_app`.`tweet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tweet_app`.`tweet` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(100) NOT NULL,
  `tweet` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `tweet_user_id_fk_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `tweet_user_id_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `tweet_app`.`user` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
